# Final Project Part 1 - Proposal
Yapa M H I B Gunaratne (Hiran Gunaratne)

## Introduction
I will be using forest fire dataset from Department of Information Systems, University of Minho, Portugalb. This dataset represent meteorological and other data collected on fires broke out in the northeast region of Portugal in year 2007

## Hypothesis
I will explore this dataset to identify which variables may affect the size of the area the fire has broke out and finally build a model to predict the size of the area of fire

## Assumptions
I assume foreset fires in this region shows a similar pattern each year, thus analysing the dataset of the specific year will be a generalised enough to predict the future

## Goal
My goal of this project is to build a model to predict the size of the area of fire

## Risks & Limitations
Main limitation of the dataset is that its confined to 1 year. Its been over 10 years since the data was recorded. Affects of natural and "man made" changes to the environment such as global warming and deforestation may affect the accuracy of predictions for the present

## Dataset
As illustrated below, the dataset includes 12 varibles and 1 output. Variables consist of meteorological and other data collected on fires broke out. Output is the area of the fire represented in hectares. Detailed description of the variables are provided below.

   1. X - x-axis spatial coordinate within the Montesinho park map
   2. Y - y-axis spatial coordinate within the Montesinho park map 
   3. month - month of the year: 'jan' to 'dec' 
   4. day - day of the week: 'mon' to 'sun' 
   5. FFMC - FFMC index from the FWI system
   6. DMC - DMC index from the FWI system
   7. DC - DC index from the FWI system
   8. ISI - ISI index from the FWI system
   9. temp - temperature in Celsius degrees
   10. RH - relative humidity in %
   11. wind - wind speed in km/h
   12. rain - outside rain in mm/m2
   13. area - the burned area of the forest (in ha)

In [11]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path('..','data')

file_path = DATA_DIR / 'forestfires.csv'

forest_fire = pd.read_csv(file_path)

In [9]:
forest_fire.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [10]:
forest_fire.sort_values('area',ascending=False).head()

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain     area
238  6  5   sep  sat  92.5  121.1  674.4   8.6  25.1  27   4.0   0.0  1090.84
415  8  6   aug  thu  94.8  222.4  698.6  13.9  27.5  27   4.9   0.0   746.28
479  7  4   jul  mon  89.2  103.9  431.6   6.4  22.6  57   4.9   0.0   278.53
237  1  2   sep  tue  91.0  129.5  692.6   7.0  18.8  40   2.2   0.0   212.88
236  2  2   sep  sat  92.5  121.1  674.4   8.6  18.2  46   1.8   0.0   200.94